# Generated by Django 2.0.6 on 2018-06-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_id', models.IntegerField()),
                ('tags', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediumparser.Tags'),
        ),
    ]
